name: Frontend

on:
    push:
        branches:
            - main
        paths:
            - frontend/**
    pull_request:
        paths:
            - frontend/**

defaults:
    run:
        working-directory: ./frontend

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up Node
                uses: actions/setup-node@v4
                with:
                    node-version: 21
                    cache: 'npm'
                    cache-dependency-path: frontend/package-lock.json

            -   name: Install dependencies
                run: npm ci

            -   name: Lint
                run: npm run lint

            -   name: Build
                run: npm run build
